export default {
    VEDITA_STATUS_IDLE: 0,
    VEDITA_STATUS_TRIGGER: 1,
    // VEDITA_STATUS_COMMAND: 1,
    // VEDITA_STATUS_ACTION: 2,
    // VEDITA_STATUS_BUSY: 3,

    VEDITA_LANGUAGE_ID: "ID",
    VEDITA_LANGUAGE_EN: "EN"
}